//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkillShare.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SkillList
    {
        public int Id { get; set; }
        public int PersonId { get; set; }
        public int SkillId { get; set; }
        public int LevelId { get; set; }
    
        public virtual Person Person { get; set; }
        public virtual Skill Skill { get; set; }
        public virtual Level Level { get; set; }
    }
}
